-- Create a test designer for web-mobile category
INSERT INTO designers (
  email,
  first_name,
  last_name,
  title,
  city,
  country,
  years_experience,
  design_philosophy,
  is_verified,
  is_approved,
  primary_categories,
  secondary_categories,
  style_keywords,
  preferred_industries,
  preferred_project_sizes,
  turnaround_times,
  collaboration_style,
  current_availability,
  portfolio_projects
) VALUES (
  'test.designer@onedesigner.app',
  'Sarah',
  'Johnson',
  'Senior UI/UX Designer',
  'San Francisco',
  'USA',
  7,
  'I believe in creating intuitive, user-centered designs that balance aesthetics with functionality.',
  true,
  true,
  ARRAY['web-mobile', 'branding-logo'],
  ARRAY['presentations'],
  ARRAY['minimal', 'modern', 'clean', 'user-friendly'],
  ARRAY['tech', 'e-commerce', 'fashion', 'health'],
  ARRAY['small', 'medium', 'large'],
  '{"web-mobile": 14, "branding-logo": 7}'::jsonb,
  'milestone-based',
  'available',
  '[{"title": "E-commerce Platform", "category": "web-mobile", "url": "portfolio.com/ecommerce"}, {"title": "Fashion Brand Identity", "category": "branding-logo", "url": "portfolio.com/fashion"}]'::jsonb
) ON CONFLICT (email) DO UPDATE SET
  is_approved = true,
  is_verified = true,
  current_availability = 'available';